language: node_js

node_js:
  - "10"

branches:
  only:
    - master
    - develop

script:
  - npm ci
  - npm run lint
  - npm run build

cache:
  npm: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: develop

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
