language: node_js

node_js:
  - "10"

branches:
  only:
    - develop

script:
  - npm ci
  - npm run lint
  - npm run build
  - npm run deploy

cache:
  npm: true
  directories:
    - "node_modules"

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
